[tool.poetry]
name = "atbs"
version = "0.1.0"
description = ""
authors = ["Deri Taufan <dtaufan@navan.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
